Update Readmi
Olympic-code/MedCare pull request #30
Opened 2022-11-23 01:39 UTC by BrunoMartinns

MedCare Project Readmi Update.
Added some information about the software.

2022-11-23 01:40 UTC, BrunoMartinns commented
Prenez-le là 
Je ne peux plus supporter de faire ça.
wiwi

2022-11-23 03:42 UTC, C03lh0 requested changes

2022-11-23 03:42 UTC, C03lh0 commented on README.md
> +	C#
Create a topic for programming language.
For example: 
 ##Programming language
     - C#
     - xmal

2022-11-23 03:42 UTC, C03lh0 commented on README.md
> +	SQLite
Create a topic for database.
For example: 
 ##Database
     - SQLite

2022-11-24 00:55 UTC, C03lh0 approved these changes

2022-11-24 03:31 UTC, aquilesRod approved these changes

2022-11-24 03:31 UTC, merged